apiVersion: v1
kind: Service
metadata:
  name: external-postgre
spec:
  type: ExternalName
  externalName: 172.17.128.1
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-postgre
subsets:
  - addresses:
    - ip: 172.17.128.1
    ports:
    - port: 5432