apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: keycloak
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:23.0.3
          args: ["start","--hostname-strict","false","--http-enabled","true"]
          envFrom:
          - configMapRef:
              name: keycloak-config
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
---
apiVersion: v1
metadata:
  name: keycloak-config
kind: ConfigMap
data:
  KC_DB_URL: jdbc:postgresql://postgresql:5432/postgres
  KC_DB_USERNAME: postgres
  KC_DB_PASSWORD: postgres
  KC_DB_SCHEMA: public
  KC_FEATURES: preview
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: admin
  KC_PROXY: edge
  KC_DB: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  type: ExternalName
  externalName: host.docker.internal