server:
  port: 8080
spring:
  application:
    name: ${APPLICATION_NAME:spring-security-keycloak}
keycloak:
  auth-server-url: http://localhost:8282
  realm: demo
  resource: backend
  public-client: true
