server:
  port: 8080
spring:
  application:
    name: ${APPLICATION_NAME:spring-security-keycloak}
keycloak:
#  auth-server-url: http://localhost:8282/auth
#  realm: demo
#  resource: backend
#  public-client: true
  auth-server-url: http://localhost:8484/auth
  realm: my_realm
  resource: my_client
  public-client: true